#!/usr/bin/with-contenv bash
#shellcheck shell=bash

  set -o pipefail
  set -e

  # Listens for the output of acarsdec (UDP), and makes it available for multiple processes at TCP port 15550
  # shellcheck disable=SC2016
  socat -u udp-listen:5550,fork stdout | ncat -4 --keep-open --listen 0.0.0.0 15550 \
  2>&1 | stdbuf -oL awk '{print "[acars_server] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

  sleep 5
