#!/command/with-contenv bash
#shellcheck shell=bash

# Listens for the output of acarsdec (UDP), and makes it available for multiple processes at TCP port 15550

socat -u udp-listen:5550,fork stdout | ncat -4 --keep-open --listen 0.0.0.0 15550

sleep 5
