#!/command/with-contenv bash
# shellcheck shell=bash

SCRIPT_NAME="$(basename "$0")"
SCRIPT_NAME="${SCRIPT_NAME%.*}"

# shellcheck disable=SC2034
s6wrap=(s6wrap --quiet --timestamps --prepend="$SCRIPT_NAME" --args)

# Require that acars_server is running
if ! netstat -an | grep -P '^\s*tcp\s+\d+\s+\d+\s+0\.0\.0\.0:15550\s+(?>\d{1,3}\.{0,1}){4}:\*\s+LISTEN\s*$' > /dev/null; then
  sleep 1
  if [[ ! ${QUIET_LOGS,,} =~ true ]]; then
    # shellcheck disable=SC2154
    "${s6wrap[@]}" echo "acars_server not running, exiting"
  fi
  exit
fi
set -e

SERVER_ADDR="UDP:${SERVER}:${SERVER_PORT}"

if [[ ! ${QUIET_LOGS,,} =~ true ]]; then
    "${s6wrap[@]}" echo "Starting acars_feeder with ${SERVER_ADDR}"
fi

# shellcheck disable=SC2016
socat -d TCP:127.0.0.1:15550 "$SERVER_ADDR"

sleep 5
