#!/command/with-contenv bash
#shellcheck shell=bash

# shellcheck disable=SC1091
source /scripts/common

ACARS_BIN="/usr/local/bin/acarsdec"
# shellcheck disable=SC2001
SOAPYSDR=""

FREQ_STRING=""

if [ -z "$GAIN" ]; then
    GAIN="-10"
else
    GAIN="$(awk '{if ($1 > 0 && $1 < 100) printf "%i", $1 * 10; else printf "%i", $1;}' <<< "$GAIN")"
fi

ACARS_CMD=("-g" "$GAIN" "-i" "$FEED_ID")

if [ -n "${CENTER_FREQ}" ]; then
	ACARS_CMD+=("-c" "$CENTER_FREQ")
fi

if [ -n "${PPM}" ]; then
	ACARS_CMD+=("-p" "$PPM")
fi

if [ -n "${SERVER}" ]; then
	ACARS_CMD+=("-o" "0")
	ACARS_CMD+=("-l" "/dev/null")
else
	ACARS_CMD+=("-o" "4")
	ACARS_CMD+=("-v")
fi

if [ -n "${RTLMULT}" ]; then
	ACARS_CMD+=("-m" "$RTLMULT")
fi

if [ -n "${VERBOSE}" ]; then
	ACARS_CMD+=("-v")
fi

# Send output JSON to acars_server
if [ -n "${SERVER}" ]; then
	if [[ "${MODE}" == @(J|j) ]]; then
		ACARS_CMD+=("-j" "127.0.0.1:5550")
	elif [[ "${MODE}" == @(P|p) ]]; then
		ACARS_CMD+=("-n" "127.0.0.1:5550")
	elif [[ "${MODE}" == @(A|a) ]]; then
		ACARS_CMD+=("-N" "127.0.0.1:5550")
	fi
fi

# Specify SOAPYSDR
if [ -n "${SOAPYSDR}" ]; then
	ACARS_CMD+=("-d" "$SOAPYSDR")
fi

if [[ -n "$ACARSDEC_COMMAND_EXTRA" ]]; then
	ACARS_CMD+=("$ACARSDEC_COMMAND_EXTRA")
fi

if [[ ${QUIET_LOGS,,} =~ true ]]; then
	ACARS_CMD+=("-l" "/dev/null")
fi

# shellcheck disable=SC2206
ACARS_CMD+=($FREQ_STRING)

set -eo pipefail

# shellcheck disable=SC2154
"${s6wrap[@]}" echo "Starting: '$ACARS_BIN" "${ACARS_CMD[*]}'"

if [[ ${QUIET_LOGS,,} =~ true ]]; then
	# shellcheck disable=SC2016
	"${s6wrap[@]}" "$ACARS_BIN" "${ACARS_CMD[@]}" 2>&1 | \
	stdbuf -oL sed --unbuffered '/^$/d' | \
	stdbuf -oL awk '! /^dumpvdl2/' | \
	stdbuf -oL awk '! /^Sampling rate set/' | \
	stdbuf -oL awk '! /^Found \[0-9]+ device(s):/' | \
	stdbuf -oL awk '! /^  [0-9]+/' | \
	stdbuf -oL awk '! /^Using device [0-9]+/' | \
	stdbuf -oL awk '! /^Found /' | \
	stdbuf -oL awk '! /^Exact sample rate /' | \
	stdbuf -oL awk '! /^Setting sample rate/' | \
	stdbuf -oL awk '! /PLL not locked!$/' | \
	stdbuf -oL awk '! /^Center frequency set/' | \
	stdbuf -oL awk '! /^Device [#]?[0-9]+/' | \
	stdbuf -oL awk '! /^Tuner gain: /' | \
	stdbuf -oL awk '! /^Set center freq. /' | \
	stdbuf -oL awk '! /^Decoding [0-9]+ channels/' | \
	stdbuf -oL awk '! /^Allocating [0-9]+ zero-copy buffers/' | \
	stdbuf -oL awk '{print $0}'
else
	# shellcheck disable=SC2016
	"${s6wrap[@]}" "$ACARS_BIN" "${ACARS_CMD[@]}"
fi

sleep 5
