#!/command/with-contenv bash
#shellcheck shell=bash

# shellcheck disable=SC1091
source /scripts/common

ACARS_BIN="/usr/local/bin/acarsdec"
# shellcheck disable=SC2001
SOAPYSDR=""

FREQ_STRING=""

ACARS_CMD=("-i" "$FEED_ID")

if [ -n "${CENTER_FREQ}" ]; then
	ACARS_CMD+=("-c" "$CENTER_FREQ")
fi

# if [[ -n "${SERVER}" ]] || [[ -n "$OUTPUT_SERVER" ]]; then
# 	ACARS_CMD+=("-o" "0")
# 	ACARS_CMD+=("-l" "/dev/null")
# else
# 	ACARS_CMD+=("-o" "4")
# 	ACARS_CMD+=("-v")
# fi

if [ -n "${VERBOSE}" ]; then
	ACARS_CMD+=("-v")
fi

# Send output JSON to acars-bridge

if [[ "${MODE}" == @(J|j) ]]; then
	ACARS_CMD+=("--output" "json:udp:host=127.0.0.1,port=5550")
elif [[ "${MODE}" == @(P|p) ]]; then
	ACARS_CMD+=("--output" "pp:udp:host=127.0.0.1,port=5550")
elif [[ "${MODE}" == @(A|a) ]]; then
	ACARS_CMD+=("--output" "native:udp:host=127.0.0.1,port=5550")
fi

# loop through the SOAPYSDR string and split on spaces
if [[ -n "${SOAPYSDR}" ]]; then
	IFS=' ' read -ra SOAPYSDR_PROCESSED <<< "${SOAPYSDR}"
	# ACARS_CMD+=("${SOAPYSDR_PROCESSED[@]}") # used for acarsdec < 4.0
	ACARS_CMD+=("--soapysdr" "${SOAPYSDR_PROCESSED[@]}")
	if [[ ${SOAPYSDR} == *"airspy"* ]] && [[ -z "${RTLMULT}" ]]; then
		# airspy runs at 3MSPS so needs a different sample rate multiplier
		RTLMULT="240"
	fi
fi

if [[ -z "${RTL_SERIAL}" ]] && [[ -n "${SERIAL}" ]]; then
    # if RTL_SERIAL not set, use legacy env var SERIAL
    RTL_SERIAL="${SERIAL}"
fi


if [[ -n "${RTL_SERIAL}" ]]; then
	ACARS_CMD+=("--rtlsdr" "${RTL_SERIAL}")
    if chk_enabled "${BIASTEE}"; then
        ACARS_CMD+=("-B" "1")
    else
        ACARS_CMD+=("-B" "0")
    fi
fi

if [ -n "${PPM}" ]; then
	ACARS_CMD+=("-p" "$PPM")
fi

if [ -z "$GAIN" ]; then
    GAIN="-10"
fi

ACARS_CMD+=("-g" "$GAIN")

if [[ -n "$ACARSDEC_COMMAND_EXTRA" ]]; then
	ACARS_CMD+=("$ACARSDEC_COMMAND_EXTRA")
fi

if [ -n "${RTLMULT}" ]; then
    ACARS_CMD+=("-m" "$RTLMULT")
fi

# shellcheck disable=SC2206
ACARS_CMD+=($FREQ_STRING)

# shellcheck disable=SC2154
"${s6wrap[@]}" echo "Starting: '$ACARS_BIN" "${ACARS_CMD[*]}'"

if chk_enabled "${QUIET_LOGS}"; then
	# shellcheck disable=SC2016
	FILTER_TERMS+=("-e" "Found .* tuner")
	FILTER_TERMS+=("-e" "Setting sample rate")
	FILTER_TERMS+=("-e" "Setting bandwidth")
	FILTER_TERMS+=("-e" "Starting, decoding .* channels")
	FILTER_TERMS+=("-e" "Exact sample rate is: ")
	exec "${s6wrap[@]}" "$ACARS_BIN" "${ACARS_CMD[@]}" > >(grep --line-buffered -v "${FILTER_TERMS[@]}")
else
	# shellcheck disable=SC2016
	exec "${s6wrap[@]}" "$ACARS_BIN" "${ACARS_CMD[@]}"
fi

sleep 5
