#!/command/with-contenv bash
#shellcheck shell=bash

SCRIPT_NAME="$(basename "$0")"
SCRIPT_NAME="${SCRIPT_NAME%.*}"

# shellcheck disable=SC2034
s6wrap=(s6wrap --quiet --timestamps --prepend="$SCRIPT_NAME" --args)

# Listens for the output of acarsdec (UDP), and makes it available for multiple processes at TCP port 15550

"${s6wrap[@]}" socat -u udp-listen:5550,fork stdout | ncat -4 --keep-open --listen 0.0.0.0 15550

sleep 5
