#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# STARTUP SEQUENCE
#  - acarsdec does not depend on any services and should start immediately

ACARS_BIN="/usr/local/bin/acarsdec"
DEVICE_ID=""
# shellcheck disable=SC2001

if [ -z "$GAIN" ]; then
    GAIN="-10"
fi

ACARS_CMD=("-g" "$GAIN" "-i" "$STATION_ID")

if [ -n "${PPM}" ]; then
	ACARS_CMD+=("-p" "$PPM")
fi

if [ -n "${QUIET_LOGS}" ]; then
	ACARS_CMD+=("-o" "0")
	ACARS_CMD+=("-l" "/dev/null")
else
	ACARS_CMD+=("-o" "4")
	ACARS_CMD+=("-v")
fi

if [ -n "${RTLMULT}" ]; then
	ACARS_CMD+=("-m" "$RTLMULT")
fi

# Send output JSON to acars_server
ACARS_CMD+=("-j" "$ACARSHUB_SERVER:5550")

# Specify device ID
if [ -n "${DEVICE_ID}" ]; then
	ACARS_CMD+=("-r" "$DEVICE_ID")
fi

# shellcheck disable=SC2206
ACARS_CMD+=($FREQUENCIES)

set -eo pipefail

echo "[acarsdec-$DEVICE_ID] Starting: '$ACARS_BIN" "${ACARS_CMD[*]}'"

# shellcheck disable=SC2016
"$ACARS_BIN" "${ACARS_CMD[@]}" \
2>&1 | stdbuf -oL sed --unbuffered '/^$/d' | stdbuf -oL awk '{print "[acarsdec] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

sleep 5
