#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# STARTUP SEQUENCE
#  - acarsdec does not depend on any services and should start immediately

ACARS_BIN="/usr/local/bin/acarsdec"
# shellcheck disable=SC2001
DEVICE_ID=""
FREQ_STRING=""

if [ -z "$GAIN" ]; then
    GAIN="-10"
fi

ACARS_CMD=("-g" "$GAIN" "-i" "$FEED_ID")

if [ -n "${PPM}" ]; then
	ACARS_CMD+=("-p" "$PPM")
fi

if [ -n "${SERVER}" ]; then
	ACARS_CMD+=("-o" "0")
	ACARS_CMD+=("-l" "/dev/null")
else
	ACARS_CMD+=("-o" "4")
	ACARS_CMD+=("-v")
fi

if [ -n "${RTLMULT}" ]; then
	ACARS_CMD+=("-m" "$RTLMULT")
fi

# Send output JSON to acars_server
if [ -n "${SERVER}" ]; then
	if [[ "${MODE}" == @(J|j) ]]; then
		ACARS_CMD+=("-j" "127.0.0.1:5550")
	elif [[ "${MODE}" == @(P|p) ]]; then
		ACARS_CMD+=("-n" "127.0.0.1:5550")
	elif [[ "${MODE}" == @(A|a) ]]; then
		ACARS_CMD+=("-N" "127.0.0.1:5550")
	fi
fi

# Specify device ID
if [ -n "${DEVICE_ID}" ]; then
	ACARS_CMD+=("-r" "$DEVICE_ID")
fi

# shellcheck disable=SC2206
ACARS_CMD+=($FREQ_STRING)

set -eo pipefail

echo "[acarsdec-$DEVICE_ID] Starting: '$ACARS_BIN" "${ACARS_CMD[*]}'"

# shellcheck disable=SC2016
"$ACARS_BIN" "${ACARS_CMD[@]}" \
2>&1 | stdbuf -oL sed --unbuffered '/^$/d' | stdbuf -oL awk '{print "[acarsdec] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

sleep 5
