#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# FEED_ID needs to be set

if [[ -z "${FEED_ID}" ]]; then
	echo "FEED_ID is not set, exiting"
	exit 1
fi

# FREQUENCIES needs to be set

if [[ -z "${FREQUENCIES}" ]]; then
	echo "FREQUENCIES is not set, exiting"
	exit 1
fi

IFS=';'
read -ra SPLIT_FREQS <<< "${FREQUENCIES}"

# loop through SPLIT_FREQS

# We can only have 8 total frequencies

if [[ "${#SPLIT_FREQS[@]}" -gt 8 ]]; then
	echo "FREQUENCIES may not contain more than 8 frequencies, exiting"
	exit 1
fi

# FREQUENCIES needs to be in the range of 118.0 - 137.0.

FREQ_STRING=""
for i in "${SPLIT_FREQS[@]}"
do
:
if [[ $(echo "$i > 118.0" | bc)  -eq 0 || $(echo "$i < 137.0" | bc) -eq 0 ]]; then
	echo "FREQUENCY $i is not in the range of 118.0 - 137.0, exiting"
	exit 1
fi
FREQ_STRING+=" $i"
done

# Make sure mode is valid

if [[ "${MODE}" != @(J|j|P|p|A|a) ]]; then
	echo "MODE is not valid, exiting"
	exit 1
fi

if [[ -n "${SERVER}" && -z "${SERVER_PORT}" ]]; then
	echo "SERVER is set but SERVER_PORT is not set, exiting"
	exit 1
fi

# SERIAL needs to be set

if [[ -z "${SERIAL}" ]]; then
	echo "SERIAL is not set, exiting"
	exit 1
fi

IFS=$'\n' RTL_TEST_OUTPUT=( $(timeout 1s rtl_test -d 0 2>&1 | grep -P '^\s+\d+:\s.*?,.*?,\s+SN:\s+.*?$' | IFS=$'\n' sed -n 's/^\s*\([^:]*\):[^,]*,[^,]*,\s*SN:\s*\(.*\)$/\1,\2/; s/\s*$//p' || true) )
for RTL_TEST_OUTPUT_LINE in "${RTL_TEST_OUTPUT[@]}"; do
        [[ "${RTL_TEST_OUTPUT_LINE##*,}" == "$SERIAL" ]] && OUTPUT_DEVICE_ID="${RTL_TEST_OUTPUT_LINE%%,*}" || true
done

if [[ -z "${OUTPUT_DEVICE_ID}" ]]; then
        echo "Could not find Device ID for serial '$SERIAL'"
        exit 1
fi

rm -rf /etc/services.d/acarsdec/run > /dev/null 2>&1
if [[ -n "${OUTPUT_DEVICE_ID}" ]]; then
	cp /etc/templates/run /etc/services.d/acarsdec/run
else
	cp /etc/templates/bad /etc/services.d/acarsdec/run
fi

s6-chmod 0755 /etc/services.d/acarsdec/run

mkdir -p /run/acars
touch /run/acars/acars.past5min.json

sed -i "s/DEVICE_ID=\"\"/DEVICE_ID=\"$OUTPUT_DEVICE_ID\"/g" /etc/services.d/acarsdec/run
sed -i "s/FREQ_STRING=\"\"/FREQ_STRING=\"$FREQ_STRING\"/g" /etc/services.d/acarsdec/run

# Everything is good to go. Exit with 0

exit 0
