---
name: Lint

on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  # =====================================================================
  # Primary Lint job
  # =====================================================================
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run flake pre-commit hooks
        run: nix develop -c pre-commit run --all-files
